#!/bin/bash
echo "🚀 JobHunter Application Package Quick Start"
echo "============================================="
echo ""
echo "📊 Package Contents:"
echo "   📄 $(ls *.tex | wc -l) LaTeX files ready for compilation"
echo "   🏢 16 Gothenburg priority positions"
echo "   ⭐ 10 high-match additional positions"
echo ""
echo "🔧 Choose compilation method:"
echo "   1. Type: ./overleaf_guide.sh (for online compilation)"
echo "   2. Type: ./compile_local.sh (for local compilation)"
echo "   3. Read: README.md (for detailed instructions)"
echo ""
echo "🎯 Recommended: Start with Overleaf for easiest PDF generation!"
